/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v7.0
processor: MKE02Z16xxx4
package_id: MKE02Z16VFM4
mcu_data: ksdk2_0
processor_version: 7.0.1
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_port.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '18', peripheral: UART0, signal: RX, pin_signal: PTB0/KBI0_P4/UART0_RX/ADC0_SE4}
  - {pin_num: '17', peripheral: UART0, signal: TX, pin_signal: PTB1/KBI0_P5/UART0_TX/ADC0_SE5}
  - {pin_num: '7', peripheral: I2C0, signal: SCL, pin_signal: PTB7/I2C0_SCL/EXTAL}
  - {pin_num: '8', peripheral: I2C0, signal: SDA, pin_signal: PTB6/I2C0_SDA/XTAL}
  - {pin_num: '28', peripheral: UART1, signal: RX, pin_signal: PTC6/UART1_RX}
  - {pin_num: '27', peripheral: UART1, signal: TX, pin_signal: PTC7/UART1_TX}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
    /* pin 7,8 is configured as I2C0_SCL, I2C0_SDA */
    PORT_SetPinSelect(kPORT_I2C0, kPORT_I2C0_SCLPTB7_SDAPTB6);
    /* pin 18,17 is configured as UART0_RX, UART0_TX */
    PORT_SetPinSelect(kPORT_UART0, kPORT_UART0_RXPTB0_TXPTB1);

    SIM->SOPT = ((SIM->SOPT &
                  /* Mask bits to zero which are setting */
                  (~(SIM_SOPT_RXDFE_MASK)))

                 /* UART0_RX Filter Select: UART0_RX input signal is connected to UART0 module directly. */
                 | SIM_SOPT_RXDFE(SOPT_RXDFE_0b0));
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
